### ISSUE TITLE
RFE:  GCP Batch API for moving routes, forwarding rules

### ISSUE THREAD

**Issue by jtylershaw** [f5devcentral/f5-cloud-failover-extension#12]
GCP has a batch API which can be used to modify objects within GCP.  If a customer has a large number of forwarding rules the failover time is high.  A batch process would reduce the amount of time it takes for a failover to happen.

This blog post (https://developers.googleblog.com/2018/03/discontinuing-support-for-json-rpc-and.html) which references an API endpoint that will be decommissioned in favor of more specific APIs talks about the batch process.  

The specific API endpoint for forwarding Rules is this: 
 https://cloud.google.com/compute/docs/reference/rest/v1/forwardingRules/setTarget

**Comment by shyawnkarim** [comment]
Thank you for reaching out to us with this idea. We have looked into this and have come to the conclusion that their batch API might speed up failover times.

**Comment by cah-roger-bauer** [comment]
Any word on this?   Is this something that is actively being pursued?   Failover times in the minutes are not an acceptable solution.  We have a working HA solution via the GTM  but its cumbersome to manage and dont not provide HA for APM.   We really need a solution that fails over quickly.

**Comment by shyawnkarim** [comment]
We looked into implementing the GCP batch API but ended up not using it. Using the batch API does not materially make a difference with failover times, like we originally thought it might.

Since looking at this, a new solution has been presented to us from GCP engineering. This new method will hopefully be available with our next release.  Internal ID AUTOSDK-204.
